#!/bin/bash

echo ""
echo "========================================="
echo "ADD THESE TO YOUR .env.local FILE:"
echo "========================================="
echo ""
echo "# Supabase Configuration (REQUIRED!)"
echo "NEXT_PUBLIC_SUPABASE_URL=https://your-project-id.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here"
echo "SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here"
echo ""
echo "========================================="
echo "To get these values:"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to Settings → API"
echo "4. Copy the values:"
echo "   - Project URL"
echo "   - anon/public key"
echo "   - service_role key"
echo "========================================="
echo ""
echo "After adding these, restart your dev server:"
echo "npm run dev"
echo ""